services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - hello-app
    networks:
      - frontend

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - backend

  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pass
    depends_on:
      - mysql
    networks:
      - frontend
      - backend

  hello-app:
    image: ghcr.io/haidamarese/hello-app:latest
    restart: always
    networks:
      - frontend

networks:
  frontend:
  backend:
